<a href="https://colab.research.google.com/github/rongxie2023/dlcv/blob/main/Chapter02/01-Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# tensor基础

In [2]:
import torch
import numpy as np

### 1 创建

In [2]:
a = torch.tensor([[1, 2, 3], [4, 5, 6]])
# a = torch.tensor([[1, 2, 3], [4, 5, 6]],dtype=torch.float32)

a
# print(a)
# display(a)

#形状
print(a.reshape(2,3))
print(a.reshape(2,-1))
print("shape:",a.shape)
print("size:",a.size())
print("dim",a.dim())

#数据类型
# torch.int8 16 32 64
# torch.float16 32 64

#两种数据类型转换方法
a = torch.tensor([[3, 4],[1, 2]], dtype=torch.int)
b = a.to(torch.float)  
c = a.float()  #b.int()
print(a.dtype)
print(b.dtype)

#cpu和gpu的移动
a = torch.tensor([[3, 4],[1, 2]]) #默认在cpu
# a = torch.tensor([[3, 4],[1, 2]],device="cuda:0") #保存到gpu

print(a.device)
b = a.to("cuda")
print(b.device)
c = a.cpu()
print(c.device)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])
shape: torch.Size([2, 3])
size: torch.Size([2, 3])
dim 2
torch.int32
torch.float32
cpu
cuda:0
cpu


In [3]:
x = torch.empty(size=(3, 3))  # Tensor of shape 3x3 with uninitialized data
x = torch.zeros((3, 3))  # Tensor of shape 3x3 with values of 0
x = torch.rand((3, 3))  # Tensor of shape 3x3 with values from uniform distribution in interval [0,1)
x = torch.ones((3, 3))  # Tensor of shape 3x3 with values of 1
x = torch.eye(5, 5)  # Returns Identity Matrix I, (I <-> Eye), matrix of shape 2x3
x = torch.arange(start=0, end=5, step=1)  # Tensor [0, 1, 2, 3, 4], note, can also do: torch.arange(11)
x = torch.linspace(start=0.1, end=1, steps=10)  # x = [0.1, 0.2, ..., 1]
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)  # Normally distributed with mean=0, std=1  正态分布
x = torch.empty(size=(1, 5)).uniform_(0, 1)  # Values from a uniform distribution low=0, high=1  均匀分布
x = torch.diag(torch.ones(3))  # Diagonal matrix of shape 3x3  

### 2 tensor与numpy互转

In [4]:
a = np.zeros((5, 5))
b = torch.from_numpy(a)

# b=torch.tensor(a)
print(b)
c= b.numpy()
print(type(b))
print(type(c))

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
<class 'torch.Tensor'>
<class 'numpy.ndarray'>


### 3 数学运算

In [5]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])

#与标量scalar的计算
print(x+2)
print(x**0.5)

# -- 加减乘除 相同位置的元素进行运算--
z1 = torch.empty(3)
torch.add(x, y, out=z1)  # This is one way
z2 = torch.add(x, y)  # This is another way
z1 = x + y  # This is my preferred way, simple and clean.
z2= x+3
print(z1)
print(z2)
print(x/y)

# -- 逻辑运算--
print(x>3)
print(x<y)


tensor([3, 4, 5])
tensor([1.0000, 1.4142, 1.7321])
tensor([5, 7, 9])
tensor([4, 5, 6])
tensor([0.2500, 0.4000, 0.5000])
tensor([False, False, False])
tensor([True, True, True])


In [6]:
# -- Inplace 操作 --
t = torch.zeros(3)

t.add_(x)  # Whenever we have operation followed by _ it will mutate the tensor in place
t += x  # Also inplace: t = t + x is not inplace, bit confusing.

In [7]:
# --数学函数
z = x.pow(2)  # z = [1, 4, 9]
z = x**2  # z = [1, 4, 9]
print(torch.sqrt(x))
print(torch.sin(x))
print(torch.log(x))

tensor([1.0000, 1.4142, 1.7321])
tensor([0.8415, 0.9093, 0.1411])
tensor([0.0000, 0.6931, 1.0986])


In [8]:
# -- 矩阵乘法 --
x1 = torch.tensor([[1,2],[3,4]])
x2 =  torch.tensor([[1,1],[2,2]])
x3 = torch.mm(x1, x2)  # Matrix multiplication of x1 and x2, out shape: 2x3
x3 = x1.mm(x2)  # Similar as line above
x4 = x1@x2

print(x3)
print(x4)

# -- 元素相同位置乘 --
z = x1 * x2
print(z)

# -- 向量内积 --
z = torch.dot(x, y)  # Dot product, in this case z = 1*9 + 2*8 + 3*7
print(z)

# -- 转置 --
print(x1.T)

# -- 逆 --
print(x1.float().inverse())


tensor([[ 5,  5],
        [11, 11]])
tensor([[ 5,  5],
        [11, 11]])
tensor([[1, 2],
        [6, 8]])
tensor(32)
tensor([[1, 3],
        [2, 4]])
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])


In [9]:
# -- Batch Matrix Multiplication --
batch = 32
n = 10
m = 20
p = 30
tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2)  # Will be shape: (b x n x p)

print(out_bmm.size())


torch.Size([32, 10, 30])


### 4 广播

In [10]:
x1 = torch.full((4, 2), 3)
x2 = torch.full((1, 2),2)
z = x1-x2  # Shape of z is 5x5: How? The 1x5 vector (x2) is subtracted for each row in the 5x5 (x1)

print(x1)
print(x2)
print(z)

tensor([[3, 3],
        [3, 3],
        [3, 3],
        [3, 3]])
tensor([[2, 2]])
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]])


### 5 其它有用的操作

In [11]:
x=torch.arange(1,7).reshape(-1,3)
print(x)

sum_x1 = torch.sum(x)  # sum all , sum_x = 21
sum_x2 = torch.sum(x, dim=0)  # Sum of x across dim=0 x轴, sum_x =[5, 7, 9]
sum_x3 = torch.sum(x, dim=1)  # Sum of x across dim=1 y轴, sum_x = [ 6, 15]
print(sum_x1,sum_x2,sum_x3)

values, indices = torch.max(x, dim=0)  # Can also do x.max(dim=0)
values, indices = torch.min(x, dim=0)  # Can also do x.min(dim=0)
print(values, indices )

abs_x = torch.abs(x)  # Returns x where abs function has been applied to every element
z = torch.argmax(x, dim=0)  # Gets index of the maximum value  返回下标
z = torch.argmin(x, dim=0)  # Gets index of the minimum value

mean_x = torch.mean(x.float(), dim=0)  # mean requires x to be float
z = torch.eq(x, y)  # Element wise comparison, in this case z = [False, False, False]
sorted_y, indices = torch.sort(y, dim=0, descending=False)

z = torch.clamp(x, min=0)  #截断
# All values < 0 set to 0 and values > 0 unchanged (this is exactly ReLU function)
# If you want to values over max_val to be clamped, do torch.clamp(x, min=min_val, max=max_val)
print(z)

print(x[1])
print(torch.bincount(x[1]))  #计数
print(x.reshape(-1).sort()) #排序

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor(21) tensor([5, 7, 9]) tensor([ 6, 15])
tensor([1, 2, 3]) tensor([0, 0, 0])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([4, 5, 6])
tensor([0, 0, 0, 0, 1, 1, 1])
torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5, 6]),
indices=tensor([0, 1, 2, 3, 4, 5]))


### 6 索引和切片

In [12]:
x=torch.arange(1,31).reshape(-1,6)
print(x)

print(x[0,0],x[0][0])  #通过下标访问tensor元素
print(x[0,0].item())  #取出元素

###切片
print(x[0]) #取出一行
t=x[0]

print(t[1:6])  #前闭后开 [)
print(t[1:6:2])  #步长  步长必须大于0
print(t[-3:])  #末尾三个
print(t.flip(0))  #步长必须大于0, ::-1 这种翻转数组不可以用

print(x[:,2]) #取出一列
print(x[:,2:3]) #取出一列并保持维度

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])
tensor(1) tensor(1)
1
tensor([1, 2, 3, 4, 5, 6])
tensor([2, 3, 4, 5, 6])
tensor([2, 4, 6])
tensor([4, 5, 6])
tensor([6, 5, 4, 3, 2, 1])
tensor([ 3,  9, 15, 21, 27])
tensor([[ 3],
        [ 9],
        [15],
        [21],
        [27]])


In [13]:
#注意切片和reshape都是视图,不是复制，对视图上的修改，都会影响到源数据
x=torch.arange(1,13).reshape(-1,4)
print(x)

y=x[0,1:3]
print(y)
y[:]=88
print(x)

x[:,3]=99
print(x)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([2, 3])
tensor([[ 1, 88, 88,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1, 88, 88, 99],
        [ 5,  6,  7, 99],
        [ 9, 10, 11, 99]])


### 7 花式索引

In [14]:
#花式索引 fancy index
x=torch.arange(1,31).reshape(-1,6)
print(x)

print( x[[1,4,2]] )  #选出x[1], x[4] x[2]这几行
print( x[:,[0,2,1]] ) #选出 0 2 1这几列
print( x[[1,4,2],[0,2,1]] )  #选出x[1,0] x[4,2] x[2,1]这几个元素
print( x[[1,4,2]][:,[0,2,1]] ) #区域选取，选择1,4,2行的0,2,1列

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])
tensor([[ 7,  8,  9, 10, 11, 12],
        [25, 26, 27, 28, 29, 30],
        [13, 14, 15, 16, 17, 18]])
tensor([[ 1,  3,  2],
        [ 7,  9,  8],
        [13, 15, 14],
        [19, 21, 20],
        [25, 27, 26]])
tensor([ 7, 27, 14])
tensor([[ 7,  9,  8],
        [25, 27, 26],
        [13, 15, 14]])


In [15]:
#注意花式索引把数据复制到新数组，即拷贝，不是视图
x=torch.arange(1,31).reshape(-1,6)
print(x)

y=x[[1,4,2]]
y[:]=0
print(y)
print(x)

x[[1,4,2]]=0   #这个是inplace操作
print(x)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])
tensor([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30]])
tensor([[ 1,  2,  3,  4,  5,  6],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0],
        [19, 20, 21, 22, 23, 24],
        [ 0,  0,  0,  0,  0,  0]])


### 8 布尔型索引

In [16]:
torch.manual_seed(0)  # # 设置随机数种子
x=torch.randint(-5,5,(4,4))
print(x)

print(x[ x>0] )
print(x[ (x>2) | (x<=-2) & (x>=-4) ])

x=torch.randint(-5,5,(1,8))
y=torch.randint(-3,3,(1,8))
print("x=",x)
print("y=",y)
print(x[x>0])  #筛选数据  选择x中大于0的元素
print(x[y>0])  #筛选数据  选择x中 y>0的位置相同的元素

y[y>0]=999  #筛选并修改
print(y)
y[y>0]=torch.tensor([999,888])  #在相应位置进行修改
print(y)

tensor([[-1,  4, -2, -5],
        [-2,  4,  2, -2],
        [ 2, -2, -4,  1],
        [ 1,  4,  3,  1]])
tensor([4, 4, 2, 2, 1, 1, 4, 3, 1])
tensor([ 4, -2, -2,  4, -2, -2, -4,  4,  3])
x= tensor([[ 1,  3, -1, -2,  1,  4, -4, -1]])
y= tensor([[-1,  2, -2,  2,  0, -3, -2, -3]])
tensor([1, 3, 1, 4])
tensor([ 3, -2])
tensor([[ -1, 999,  -2, 999,   0,  -3,  -2,  -3]])
tensor([[ -1, 999,  -2, 888,   0,  -3,  -2,  -3]])


### 变化形状

In [17]:
x = torch.arange(9)

# Let's say we want to reshape it to be 3x3
x_3x3 = x.view(3, 3)
x_3x3 = x.reshape(3, 3)

y = x_3x3.t()
print(y)

### 合并
x1 = torch.rand(2, 5)
x2 = torch.rand(2, 5)
print(torch.cat((x1, x2), dim=0).shape)  # Shape: 4x5
print(torch.cat((x1, x2), dim=1).shape)  # Shape 2x10

### 改变张量维度顺序的方法
batch = 64
x = torch.rand((batch, 2, 5))
z = x.permute(0, 2, 1)
print(x.shape,z.shape)

### 添加一个新的维度（轴）
x = torch.arange(10)  # Shape is [10], let's say we want to add an additional so we have 1x10
print(x.unsqueeze(0).shape)  # 1x10  dim 插入新维度的位置
print(x.unsqueeze(1).shape)  # 10x1

### 移除张量大小为 1 的维度
# 创建一个形状为 (1, 5, 1) 的三维张量
x = torch.tensor([[1], [2], [3], [4], [5]]).unsqueeze(0).unsqueeze(2)
print("Original Tensor Shape:", x.shape)

# 使用 squeeze 移除所有大小为 1 的维度
squeezed_tensor = x.squeeze()
print("Squeezed Tensor Shape:", squeezed_tensor.shape)
# 使用 squeeze 移除第 0 维度上的大小为 1 的维度
squeezed_tensor_dim0 = x.squeeze(0)
print("Squeezed Tensor Shape (dim=0):", squeezed_tensor_dim0.shape)

# 使用 squeeze 移除第 2 维度上的大小为 1 的维度
squeezed_tensor_dim2 = x.squeeze(2)
print("Squeezed Tensor Shape (dim=2):", squeezed_tensor_dim2.shape)


tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
torch.Size([4, 5])
torch.Size([2, 10])
torch.Size([64, 2, 5]) torch.Size([64, 5, 2])
torch.Size([1, 10])
torch.Size([10, 1])
Original Tensor Shape: torch.Size([1, 5, 1, 1])
Squeezed Tensor Shape: torch.Size([5])
Squeezed Tensor Shape (dim=0): torch.Size([5, 1, 1])
Squeezed Tensor Shape (dim=2): torch.Size([1, 5, 1])


In [3]:
dir(torch.Tensor)

['H',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__cuda_array_interface__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__

In [5]:
help(torch.min)

Help on built-in function min in module torch:

min(...)
    min(input) -> Tensor
    
    Returns the minimum value of all elements in the :attr:`input` tensor.
    
    .. warning::
        This function produces deterministic (sub)gradients unlike ``min(dim=0)``
    
    Args:
        input (Tensor): the input tensor.
    
    Example::
    
        >>> a = torch.randn(1, 3)
        >>> a
        tensor([[ 0.6750,  1.0857,  1.7197]])
        >>> torch.min(a)
        tensor(0.6750)
    
    .. function:: min(input, dim, keepdim=False, *, out=None) -> (Tensor, LongTensor)
       :noindex:
    
    Returns a namedtuple ``(values, indices)`` where ``values`` is the minimum
    value of each row of the :attr:`input` tensor in the given dimension
    :attr:`dim`. And ``indices`` is the index location of each minimum value found
    (argmin).
    
    If :attr:`keepdim` is ``True``, the output tensors are of the same size as
    :attr:`input` except in the dimension :attr:`dim` where they 