<a href="https://colab.research.google.com/github/rongxie2023/dlcv/blob/main/Chapter02/02-Auto_gradient.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
x = torch.arange(4.0)
print(x)
print(x.requires_grad)
print(x.grad)

tensor([0., 1., 2., 3.])
False
None


In [4]:
#计算y=2 x dot x
x.requires_grad=True
y=2*x.dot(x)   #注意y必须是个标量才能自动计算梯度
print(y)

y.backward()
print(x.grad)
print(x.grad == 4 * x)

tensor(28., grad_fn=<MulBackward0>)
tensor([ 0.,  4.,  8., 12.])
tensor([True, True, True, True])


In [5]:
# 在默认情况下，PyTorch会累积梯度，我们需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

### 非标量变量的反向传播

In [6]:
# 对于非标量输出，你需要提供一个与输出张量形状相同的gradient参数给.backward()方法
# 本例只想求偏导数的和，所以传递一个1的梯度是合适的
print(x)
x.grad.zero_()
y = x * x
# 等价于y.backward(torch.ones(len(x)))
# y.backward()
y.backward(torch.ones_like(y))
# y.sum().backward()
x.grad

tensor([0., 1., 2., 3.], requires_grad=True)


tensor([0., 2., 4., 6.])