<a href="https://colab.research.google.com/github/rongxie2023/dlcv/blob/main/Chapter02/Chapter02/07-case1-knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [51]:
X=torch.tensor([[0,0],[1,1],[1.1,1],[0.1,0],[0,0]])
y=torch.tensor([2,1,1,2,2])
t=torch.tensor([0.1,0.2])
print(X)
print(y)

tensor([[0.0000, 0.0000],
        [1.0000, 1.0000],
        [1.1000, 1.0000],
        [0.1000, 0.0000],
        [0.0000, 0.0000]])
tensor([2, 1, 1, 2, 2])


In [52]:
#计算距离
dist=(X-t)**2
print(dist)
d=dist.sum(dim=1)
print(d)

tensor([[0.0100, 0.0400],
        [0.8100, 0.6400],
        [1.0000, 0.6400],
        [0.0000, 0.0400],
        [0.0100, 0.0400]])
tensor([0.0500, 1.4500, 1.6400, 0.0400, 0.0500])


In [54]:
#排序并统计票数
idx=d.argsort(descending=False)
print("距离=",d)
print("由小到大排列的下标：",idx)

#取出排好序的类别
yy=y[idx]
print("对应的类别",yy)

#统计前K个的票数
count=yy[:3].bincount()
print("前三名票数统计：",count)

#取票数最多的类别
print("票数最大值",count.max())
print("测试点对应的类别：",count.argmax().item())

距离= tensor([0.0500, 1.4500, 1.6400, 0.0400, 0.0500])
由小到大排列的下标： tensor([3, 0, 4, 1, 2])
对应的类别 tensor([2, 2, 2, 1, 1])
前三名票数统计： tensor([0, 0, 3])
票数最大值 tensor(3)
测试点对应的类别： 2
